### ISSUE TITLE
Connection between last conv layer and fc layer

### ISSUE THREAD

**Issue by xiao1228** [liuzhuang13/slimming#1]
Hi,
Thank you very much for the nice work.
I am just wondering, in your example for vgg, the last layer of conv which connected to the fc outputs 1x1 features. However, my network doesn't output a 1x1 in the last conv layer, so how should I connect the conv with fc? As the weights and output size doesnt match.
Thank you

**Comment by liuzhuang13** [comment]
Traditionally people "unroll" the feature maps (3d) into vectors (1d), for example, you have 100 4x4 feature maps, and you can just unroll them into 1600 neurons and then attach fc layers. I think you can use the "nn.View" layer to do this in Torch.

But now people typically use global average pooling at the end of the conv layers. In this case, if you have 100 4x4 feature maps, you average each 4x4 feature map and get 100 numbers, and then do attach a final fc layer (classifier).

How is your question related to this method (network slimming) or code?

**Comment by xiao1228** [comment]
Thank you very much to point out that I can use a average pooling to solve the issue!
